### ISSUE TITLE
TypeError: h.elm.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by HC-Team** [Human-Connection/WebApp#37]
https://sentry.human-connection.org/hc/webapp-ym/issues/33/

```
TypeError: h.elm.getBoundingClientRect is not a function
  at a.render (/_nuxt/vendor.995b6638351d8e94f910.js:2:1124168)
  at a.t._render (/_nuxt/vendor.995b6638351d8e94f910.js:2:1094689)
  at a.<anonymous> (/_nuxt/vendor.995b6638351d8e94f910.js:2:1125818)
  at Oe.I3G/.Oe.get (/_nuxt/vendor.995b6638351d8e94f910.js:2:1078128)
  at Oe.I3G/.Oe.run (/_nuxt/vendor.995b6638351d8e94f910.js:2:1079026)
...
(4 additional frame(s) were not displayed)
```

**Comment by appinteractive** [comment]
Seems like I killed it.
