### ISSUE TITLE
Error: Timeout of 5000ms exceeded calling follows::find

### ISSUE THREAD

**Issue by HC-Team** [Human-Connection/WebApp#38]
https://sentry.human-connection.org/hc/webapp-ym/issues/24/

```
Error: Timeout of 5000ms exceeded calling follows::find
  at None (/_nuxt/vendor.995b6638351d8e94f910.js:2:1546441)
  at i (/_nuxt/vendor.995b6638351d8e94f910.js:2:1155280)
```

**Comment by appinteractive** [comment]
fixed for the moment
